name: Build and Push Docker Image
on:
  workflow_call:
    inputs:
      latest:
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      DOCKER_REGISTRY_NAME:
        required: true


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Extract app_version from gradle.properties
        id: extract_version
        run: |
          echo "APP_VERSION=$(grep 'app_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker tags
        id: set-tags
        run: |
          echo "IMAGE_TAGS=${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:${{ env.APP_VERSION }}" >> $GITHUB_ENV
          if [ "${{ inputs.latest }}" = "true" ]; then
            echo "IMAGE_TAGS=${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:${{ env.APP_VERSION }},${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAGS }}