name: Push image and deploy to test
run-name: Pushing Docker image to container registry and deploying to test
on:
  push:
    branches: [test]
    paths-ignore:
      - 'README.md'

jobs:
  call-build-and-push-image:
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}

  deploy-image-test:
    runs-on: ubuntu-latest
    needs: call-build-and-push-image
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Extract app_version from gradle.properties
        id: extract_version
        run: |
          echo "APP_VERSION=$(grep 'app_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: kbot
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop kbot_test || true
            docker rm kbot_test || true
            docker pull ${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:${{ env.APP_VERSION }}
            docker run -d --restart=always --name kbot_test \
              -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_TEST }} \
              -e GUILD_ID=${{ secrets.GUILD_ID_TEST }} \
              -e ROLES_MESSAGE_CHANNEL_ID=${{ secrets.ROLES_MESSAGE_CHANNEL_ID_TEST }} \
              -e ROLES_MESSAGE_ID=${{ secrets.ROLES_MESSAGE_ID_TEST }} \
              -e DAILY_UPDATES_CHANNEL_ID=${{ secrets.DAILY_UPDATES_CHANNEL_ID_TEST }} \
              ${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:${{ env.APP_VERSION }}