name: Push image and deploy to prod
run-name: Pushing Docker image to container registry and deploying to prod
on:
  push:
    branches: [main]

jobs:
  deploy-image-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Extract app_version from gradle.properties
        run: |
          echo "APP_VERSION=$(grep 'app_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:${{ env.APP_VERSION }},${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script
        run: |
          ssh kbot@${{ secrets.SSH_HOST }} "./deploy.sh ${{ env.APP_VERSION }} ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_TOKEN }} kbot_prod ${{ secrets.DISCORD_TOKEN_PROD }} ${{ secrets.GUILD_ID_PROD }} ${{ secrets.ROLES_MESSAGE_CHANNEL_ID_PROD }} ${{ secrets.ROLES_MESSAGE_ID_PROD }}"

      - name: SSH cleanup
        run: |
          rm ~/.ssh/id_ed25519