name: Push image to registry
run-name: Deploying solution to container registry
on:
  push:
    branches: [main, dev]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Extract app_version from gradle.properties
        run: |
          echo "APP_VERSION=$(grep 'app_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_NAME }}/kbot:${{ env.APP_VERSION }}